### ISSUE TITLE
Reference to mon_bear_smoky causes error when CrazyCataclysm is not loaded

### ISSUE THREAD

**Issue by starlightsys** [DracoGriffin/DG_Mods#2]
https://github.com/DracoGriffin/DG_Mods/blob/cb38a88f0f3c05c42319aa804358a485838e8c5e/DracoDogMod/dog_monstergroups.json#L567

**Comment by DracoGriffin** [comment]
Thanks for your issue report! Apologize for not responding sooner, I didn't have notifications set up.

This will be fixed in the next update (#3).
